# Install pre-commit hooks via
# pre-commit install
 
repos:
# yapf = yet another python formatter
- repo: git://github.com/pre-commit/mirrors-yapf
  rev: v0.22.0
  hooks:
  - id: yapf

# prospector: collection of python linters
- repo: git://github.com/guykisel/prospector-mirror
  sha: b27f281eb9398fc8504415d7fbdabf119ea8c5e1
  hooks:
  - id: prospector
